// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"khalif-identify/internal/config"
	"khalif-identify/internal/domain"
	"khalif-identify/internal/handler"
	"khalif-identify/internal/repository"
	"khalif-identify/internal/usecase"
	"khalif-identify/pkg/utils"
)

// Injectors from wire.go:

// 3. Update InitializeApp agar me-return *App saja
func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	userRepo := repository.NewUserRepository(db)
	redisRepo := repository.NewCacheRepository(client)
	azureUploader := ProvideAzureUploader(configConfig)
	jwtSecret := ProvideJWTSecret(configConfig)
	userUseCase := NewUserUseCaseWire(userRepo, redisRepo, azureUploader, jwtSecret)
	userHandler := handler.NewUserHandler(userUseCase)
	app := NewApp(db, client, userHandler)
	return app, nil
}

// wire.go:

// 1. Buat Struct Penampung (Container)
type App struct {
	DB          *gorm.DB
	RDB         *redis.Client
	UserHandler *handler.UserHandler
}

// 2. Provider untuk membuat Struct App
func NewApp(db *gorm.DB, rdb *redis.Client, h *handler.UserHandler) *App {
	return &App{
		DB:          db,
		RDB:         rdb,
		UserHandler: h,
	}
}

// Perbaikan: Return type diganti menjadi domain.UserUseCase
func NewUserUseCaseWire(
	repo domain.UserRepository,
	cache domain.CacheRepository,
	uploader *utils.AzureUploader,
	secret JWTSecret,
) domain.UserUseCase {
	return usecase.NewUserUseCase(repo, cache, uploader, string(secret))
}
